export const advRoutes = [
  {
    component: 'adv/ProjectManager/Details',
    hideInMenu: true,
    icon: '',
    name: '项目详情',
    path: '/adv/projectManager/details',
  },
  {
    component: 'adv/ProjectManager/AddTask',
    hideInMenu: true,
    icon: '',
    name: '任务列表',
    path: '/adv/projectManager/addTask',
  },
  {
    component: 'adv/ProjectManager/AddTask/AddTaskDetail',
    hideInMenu: true,
    icon: '',
    name: '新建任务',
    path: '/adv/projectManager/addTaskDetail',
  },
  {
    component: 'adv/ProjectManager/AddTask/AddPoint',
    hideInMenu: true,
    icon: '',
    name: '点位库上传',
    path: '/adv/projectManager/AddPoint',
  },
  {
    component: 'adv/ProjectManager/AddTask/AddEmail',
    hideInMenu: true,
    icon: '',
    name: '邮件列表',
    path: '/adv/projectManager/addEmail',
  },
  {
    component: 'adv/ProjectManager/AddTask/SendEmail',
    hideInMenu: true,
    icon: '',
    name: '发送邮件',
    path: '/adv/projectManager/sendEmail',
  },
  {
    component: 'adv/ProjectManager/AddTask/PreviewTask',
    hideInMenu: true,
    icon: '',
    name: '任务预览',
    path: '/adv/projectManager/previewTask',
  },
  {
    component: 'adv/ProjectManager/AddTask/Subtasks',
    hideInMenu: true,
    icon: '',
    name: '子任务列表',
    path: '/adv/projectManager/AddTask/subtasks',
  },
  {
    component: 'adv/ApprovalCenter/Details',
    hideInMenu: true,
    icon: '',
    name: '答案详情',
    path: '/adv/approvalCenter/details',
  },
  {
    component: 'adv/ApprovalCenter/ViewReport',
    hideInMenu: true,
    icon: '',
    name: '项目报告',
    path: '/adv/approvalCenter/viewReport',
  },
  {
    component: 'adv/ApprovalCenter/FastApproval',
    hideInMenu: true,
    icon: '',
    name: '极速审批',
    path: '/adv/approvalCenter/fastApproval',
  },

]
export const businessRoutes = [
  {
    component: 'business/Customer/CustomerDetail',
    hideInMenu: true,
    icon: '',
    name: '客户数据',
    path: '/business/customer/customerDetail',
  },
  {
    component: 'business/Agent/Detail',
    hideInMenu: true,
    icon: '',
    name: '代理数据',
    path: '/business/agent/detail',
  },
]
