# 配置包管理相关规则
packages:
  # 匹配 npm 目录下的所有文件和子目录
  - 'npm/**'
  # 匹配 packages 目录下的所有一级子目录
  - 'packages/*'
  # 匹配 html-demo 目录下的所有文件和子目录
  - 'html-demo/*'
#   # 排除 lm-lint/src 目录，不进行包管理
#   - '!**/npm/lm-lint/src'
# # 覆盖默认配置规则
# overrides:
#   # 针对 lm-lint/src 目录的特殊处理，禁用链接功能
#   '**/npm/lm-lint/src':
#     link: false
#   # 针对 .gitignore 文件的特殊处理
#   '**/.gitignore':